name: Build & Push (Docker Hub)

on:
  workflow_dispatch: {}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject SSH_AUTHKEY (if provided)
        run: |
          if [ -n "${{ secrets.SSH_AUTHKEY }}" ]; then
            echo "${{ secrets.SSH_AUTHKEY }}" > authorized_keys
            echo "Injected SSH_AUTHKEY from secrets."
          else
            echo "No SSH_AUTHKEY secret; using repo authorized_keys if present."
          fi

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: n4vip/n4ssh2:latest
          platforms: linux/amd64
